workers: 0
weight_decay: 0.0005
momentum: 0.9
display: 20
max_iter: 53100
batch_size: 64
test_interval: 500
topk: 3
base_lr: 0.00002
start_iters: 0
best_model: 12345678.9

lr_policy: 'step'
gamma: 0.333
step_size: 5000
